const nav=[
 ["Home","index.html"],["Server","server.html"],["Profile","profile.html"],["Leaderboards","leaderboards.html"],
 ["Shop","shop.html"],["Wallet","wallet.html"],["Hall of Fame","hall.html"],["Staff","staff.html"],
 ["Rules","rules.html"],["Tickets","tickets.html"],["News","news.html"],["Vote","vote.html"],["Community","community.html"],["Admin","admin.html"]
];
const pages={
home:{title:"Home",body:`
<section class="hero"><div class="eyebrow">🟢 SERVER ONLINE <span>•</span> play. compete. become legend.</div>
<h1><span class="gradient">GHOST PIXSEL</span></h1><p>Where legends rise. A competitive Minecraft network built around community, events, progression and unforgettable moments.</p>
<div class="actions"><a class="btn primary" href="server.html">🎮 PLAY NOW</a><a class="btn" href="server.html">📊 SERVER STATUS</a></div></section>
<section class="section"><div class="grid stats">
${stat("🟢","Players Online","127 / 500","online")}${stat("⚡","Ping","32 ms","")}${stat("🧩","Version","1.21.x","")}${stat("🌐","Uptime","99.98%","")}
</div></section>
<section class="section"><div class="sectionhead"><h2>Why Ghost Pixsel?</h2><span class="muted">Built for players</span></div><div class="grid featuregrid">
${feature("🏆","Competitive","Ranked modes, seasonal ladders and rewards that make every match count.")}${feature("💰","Living Economy","Earn, trade and spend your way through a player-driven economy.")}${feature("🎮","Custom Modes","BedWars, events and custom experiences designed for the community.")}
</div></section>
<section class="section"><div class="sectionhead"><h2>🏆 Top Players</h2><a class="muted" href="leaderboards.html">View all →</a></div>${leaderboard()}</section>
<section class="section"><div class="sectionhead"><h2>📰 Latest News</h2><a class="muted" href="news.html">All news →</a></div><div class="grid newsgrid">
${news("🎃","Halloween Event","October 31","Limited cosmetics, quests and community rewards are coming.")}${news("⚔️","New BedWars Season","October 20","A fresh season, new maps and a reset leaderboard.")}${news("🔥","Server Update","October 12","Performance improvements and new social features.")}
</div></section>`},
server:{title:"Server Status",body:`${pageHead("Server Status","Everything you need to know before you join.")}<div class="grid stats">${stat("🟢","Status","ONLINE","online")}${stat("👥","Players","127 / 500","")}${stat("⚡","Ping","32 ms","")}${stat("🧩","Version","1.21.x","")}</div><section class="section"><div class="grid two"><div class="card"><h2>Server Modes</h2><div class="list">${row("⚔️","BedWars","Online")}${row("🌌","SkyBlock","Online")}${row("💰","Survival Economy","Online")}${row("🎯","Duels","Online")}</div></div><div class="card"><h2>Connection</h2><p class="muted">Copy the address and join from Minecraft.</p><div class="row"><strong>play.ghostpixsel.net</strong><button class="btn" onclick="copyText('play.ghostpixsel.net')">Copy</button></div></div></div></section>`},
profile:{title:"Ghost Profile",body:`${pageHead("Ghost Profile","Your progression, achievements and server identity.")}<div class="grid two"><div class="card"><div style="font-size:60px">👻</div><h2>ALPHA</h2><p class="muted">Level 42 • Member since 2026</p><div class="progress"><i style="width:72%"></i></div><p class="muted">7,200 / 10,000 XP</p></div><div class="card"><h2>Stats</h2>${row("💰","Balance","2,450,000")}${row("⏱️","PlayTime","184h 22m")}${row("🏆","Achievements","37")}${row("⚔️","BedWars Wins","128")}</div></div><section class="section"><div class="card"><h2>Recent Achievements</h2><div class="list">${row("🔥","First Win","Unlocked")}${row("🏅","100 Wins","Unlocked")}${row("👑","Top 10","Unlocked")}</div></div></section>`},
leaderboards:{title:"Leaderboards",body:`${pageHead("Leaderboards","Compete. Climb. Become a legend.")}<div class="card">${leaderboard(true)}</div>`},
shop:{title:"Shop",body:`${pageHead("Ghost Shop","Ranks, cosmetics and premium perks.")}<div class="grid pricegrid">${price("WRAITH","$4.99",["Wraith prefix","3 cosmetics","7-day kit"])}${price("PHANTOM","$9.99",["Phantom prefix","8 cosmetics","Monthly kit","Priority queue"],true)}${price("LEGEND","$19.99",["Legend prefix","All cosmetics","Monthly kit","VIP events"])}</div>`},
wallet:{title:"Wallet & Payment",body:`${pageHead("Wallet & Payment","Manage balance, rewards and referrals.")}<div class="grid two"><div class="card"><h2>💳 Wallet</h2><div class="stat"><div class="label">Available Balance</div><div class="value">$24.50</div></div><button class="btn primary" onclick="toast('Checkout flow ready for backend integration.')">Add Funds</button></div><div class="card"><h2>🎁 Referral</h2><p class="muted">Share your code and earn rewards.</p><div class="row"><strong>ALPHA-GHOST</strong><button class="btn" onclick="copyText('ALPHA-GHOST')">Copy</button></div></div></div>`},
hall:{title:"Hall of Fame",body:`${pageHead("Hall of Fame","The players who shaped Ghost Pixsel.")}<div class="grid featuregrid">${feature("👑","Season 01 Champion","NightGhost — 14,820 rating")}${feature("⚔️","BedWars Legend","VoidWalker — 2,100 wins")}${feature("🏆","Community Hero","LunaCraft — 50 event wins")}</div>`},
staff:{title:"Staff",body:`${pageHead("Staff Team","Meet the people keeping the server alive.")}<div class="grid featuregrid">${feature("👑","OWNER","ALPHA")}${feature("🛡️","ADMIN","GhostAdmin")}${feature("🔨","MODERATOR","PixelMod")}</div>`},
rules:{title:"Rules",body:`${pageHead("Rules","Play fair. Respect people. Protect the community.")}<div class="card"><div class="list">${rule("1","Respect everyone","No harassment, hate or targeted abuse.")}${rule("2","No cheating","No hacks, unfair clients, exploits or intentional bugs.")}${rule("3","No scams","Do not deceive players in trades or payments.")}${rule("4","Keep chat clean","No spam, flooding or disruptive behavior.")}${rule("5","Follow staff decisions","Use tickets if you believe a moderation action was incorrect.")}</div></div>`},
tickets:{title:"Tickets",body:`${pageHead("Support Tickets","Need help? Send the team a ticket.")}<div class="grid two"><div class="card"><h2>Open a Ticket</h2><form class="form" onsubmit="event.preventDefault();toast('Ticket created locally. Connect a backend to persist it.');this.reset()"><input class="input" required placeholder="Subject"><select class="select"><option>General Support</option><option>Player Report</option><option>Purchase Issue</option><option>Bug Report</option></select><textarea class="textarea" required placeholder="Describe your issue..."></textarea><button class="btn primary">Submit Ticket</button></form></div><div class="card"><h2>Your Tickets</h2>${row("#1042","Shop question","Open")}${row("#1031","Bug report","Closed")}</div></div>`},
news:{title:"News & Events",body:`${pageHead("News & Events","Updates, announcements and community events.")}<div class="grid newsgrid">${news("🎃","Halloween Event","October 31","Limited quests, cosmetics and rewards.")}${news("⚔️","BedWars Season","October 20","New maps and seasonal progression.")}${news("🔥","Server Update","October 12","Performance and UI improvements.")}${news("🎁","Community Weekend","October 08","Double XP and special challenges.")}</div>`},
vote:{title:"Vote",body:`${pageHead("Vote for Ghost Pixsel","Support the server and earn in-game rewards.")}<div class="card"><h2>🗳️ Daily Vote</h2><p class="muted">Vote on the listed platforms. Each successful vote gives you rewards.</p><div class="list">${row("🌐","MinecraftServers","Vote →")}${row("🌐","ServerList","Vote →")}${row("🌐","TopG","Vote →")}</div><button class="btn primary" onclick="toast('Vote links can be connected here.')">Claim Vote Rewards</button></div>`},
community:{title:"Community",body:`${pageHead("Community","Find your squad and stay connected.")}<div class="grid featuregrid">${feature("💬","Discord","Chat, events, support and announcements.")}${feature("📸","Social","Share clips, builds and achievements.")}${feature("🎮","In Game","Meet players directly on the network.")}</div>`},
admin:{title:"Admin Panel",body:`${pageHead("Admin Panel","Management dashboard — connect to your secure backend.")}<div class="grid stats">${stat("👥","Players","12,481","")}${stat("🎫","Open Tickets","18","")}${stat("🚨","Reports","6","")}${stat("💳","Revenue","$8,420","")}</div><section class="section"><div class="card"><h2>Quick Actions</h2><div class="actions" style="justify-content:flex-start"><button class="btn" onclick="toast('Maintenance toggle placeholder')">Maintenance</button><button class="btn" onclick="toast('Broadcast placeholder')">Broadcast</button><button class="btn" onclick="toast('Player manager placeholder')">Players</button></div></div></section>`}
};
function stat(i,l,v,c){return `<div class="card stat"><div class="icon">${i}</div><div class="label">${l}</div><div class="value ${c}">${v}</div></div>`}
function feature(i,t,d){return `<div class="card feature"><div class="icon">${i}</div><h3>${t}</h3><p>${d}</p></div>`}
function row(a,b,c){return `<div class="row"><span>${a} <strong>${b}</strong></span><span class="badge">${c}</span></div>`}
function pageHead(t,d){return `<section class="pagehero"><h1>${t}</h1><p class="muted">${d}</p></section>`}
function news(i,t,d,p){return `<article class="card news"><div class="icon">${i}</div><div class="date">${d}</div><h3>${t}</h3><p>${p}</p><a class="muted" href="news.html">Read more →</a></article>`}
function price(t,a,items,featured=false){return `<div class="card price ${featured?'featured':''}">${featured?'<span class="badge">POPULAR</span>':''}<h3>${t}</h3><div class="amount">${a}</div><ul>${items.map(x=>`<li>✓ ${x}</li>`).join('')}</ul><button class="btn ${featured?'primary':''}" onclick="toast('${t} selected — checkout backend coming next.')">Choose Rank</button></div>`}
function rule(n,t,d){return `<div class="row"><span><strong>${n}. ${t}</strong><br><small class="muted">${d}</small></span></div>`}
function leaderboard(full=false){let data=[["#1","NightGhost","89","2,450,000"],["#2","VoidWalker","84","2,100,000"],["#3","AlphaPlayer","80","1,900,000"],["#4","LunaCraft","77","1,650,000"],["#5","PixelKing","72","1,420,000"]];return `<div class="tablewrap"><table class="table"><thead><tr><th>Rank</th><th>Player</th><th>Level</th><th>Money</th></tr></thead><tbody>${data.map(x=>`<tr><td class="rank">${x[0]}</td><td>👻 ${x[1]}</td><td>${x[2]}</td><td>💰 ${x[3]}</td></tr>`).join('')}</tbody></table></div>`}
function copyText(t){navigator.clipboard?.writeText(t);toast('Copied: '+t)}
function toast(t){const x=document.querySelector('.toast');x.textContent=t;x.style.display='block';setTimeout(()=>x.style.display='none',2200)}
function render(){
 const p=document.body.dataset.page||"home", d=pages[p]||pages.home;
 document.querySelector("#app").innerHTML=`<header><div class="container nav"><a class="brand" href="index.html"><span class="ghost">👻</span> GHOST PIXSEL</a><button class="menu" onclick="document.querySelector('.navlinks').classList.toggle('open')">☰</button><nav class="navlinks">${nav.map(n=>`<a class="${n[1].replace('.html','')===p?'active':''}" href="${n[1]}">${n[0]}</a>`).join('')}</nav></div></header><main><div class="container page">${d.body}</div></main><footer><div class="container foot"><span>👻 GHOST PIXSEL — WHERE LEGENDS RISE.</span><span>© 2026 Ghost Pixsel</span></div></footer><div class="toast"></div>`;
}
render();